version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[analysis]
  [analysis.python]
    [analysis.python.bandit]
      enabled = true  # Enable Bandit security analysis
      
[[analyzers]]
name = "secrets"
enabled = true
